log spread failures to grafana patch

diff --git a/tests/lib/external/snapd-testing-tools/tools/repack-kernel b/tests/lib/external/snapd-testing-tools/tools/repack-kernel
--- a/tests/lib/external/snapd-testing-tools/tools/repack-kernel
+++ b/tests/lib/external/snapd-testing-tools/tools/repack-kernel
@@ -1,11 +1,7 @@
 #!/bin/bash
-
-# Author: Maciej Borzecki
-# Modified by Ian Johnson <ian.johnson@canonical.com>
-
 set -e
 
-if [[ -n "$D" ]]; then
+if [ -n "$D" ]; then
     set -x
 fi
 
@@ -15,42 +11,44 @@ show_help() {
     echo "handle extraction of the kernel snap to a workspace directory, and later"
     echo "repacking it back to a snap."
     echo ""
-    echo "   setup                          - setup system dependencies"
-    echo "   extract <snap-file> <target>   - extract under <target> workspace tree"
-    echo "   prepare <target>               - prepare initramfs & kernel for repacking"
-    echo "   pack <target>                  - pack the kernel"
-    echo "   cull-firmware <target>         - remove unnecessary firmware"
-    echo "   cull-modules <target>          - remove unnecessary modules"
+    echo "   repack-kernel setup                        - setup system dependencies"
+    echo "   repack-kernel extract <snap-file> <target> - extract under <target> workspace tree"
+    echo "   repack-kernel prepare <target>             - prepare initramfs & kernel for repacking"
+    echo "   repack-kernel pack <target>                - pack the kernel"
+    echo "   repack-kernel cull-firmware <target>       - remove unnecessary firmware"
+    echo "   repack-kernel cull-modules <target>        - remove unnecessary modules"
     echo ""
 }
 
-setup_deps() {
-    if [[ "$UID" != "0" ]]; then
+setup() {
+    if [ "$UID" != "0" ]; then
         echo "run as root (only this command)"
         exit 1
     fi
 
     # carries ubuntu-core-initframfs
     add-apt-repository ppa:snappy-dev/image -y
-    apt-get update -y
-    apt-get install ubuntu-core-initramfs -y
+    apt update
+    
+    if ! dpkg -s ubuntu-core-initramfs >/dev/null 2>&1; then
+        if ! apt install -y ubuntu-core-initramfs; then
+            echo "ubuntu-core-initramfs was not available in deb repository!"
+            exit 1
+        fi
+    fi
 }
 
 get_kver() {
-    kerneldir="$1"
-    (
-        cd "$kerneldir"
-        #shellcheck disable=SC2010
-        ls "config"-* | grep -Po 'config-\K.*'
-    )
+    local kerneldir="$1"
+    find "$kerneldir" -maxdepth 1 -name "config-*" | grep -Po 'config-\K.*'
 }
 
-extract_kernel() {
+extract() {
     local snap_file="$1"
     local target="$2"
 
-    if [[ -z "$target" ]] || [[ -z "$snap_file" ]]; then
-        echo "usage: prepare <target-dir> <kernel-snap>"
+    if [ -z "$target" ] || [ -z "$snap_file" ]; then
+        echo "repack-kernel: invalid arguments for extract"
         exit 1
     fi
 
@@ -66,27 +64,21 @@ extract_kernel() {
     # repack initrd magic, beware
     # assumptions: initrd is compressed with LZ4, cpio block size 512, microcode
     # at the beginning of initrd image
-    (
-        cd "$target/kernel"
 
-        # XXX: ideally we should unpack the initrd, replace snap-boostrap and
-        # repack it using ubuntu-core-initramfs --skeleton=<unpacked> this does not
-        # work and the rebuilt kernel.efi panics unable to start init, but we
-        # still need the unpacked initrd to get the right kernel modules
-        objcopy -j .initrd -O binary kernel.efi "$target/work/initrd"
+    # XXX: ideally we should unpack the initrd, replace snap-boostrap and
+    # repack it using ubuntu-core-initramfs --skeleton=<unpacked> this does not
+    # work and the rebuilt kernel.efi panics unable to start init, but we
+    # still need the unpacked initrd to get the right kernel modules
+    objcopy -j .initrd -O binary "$target"/kernel/kernel.efi "$target/work/initrd"
 
-        # copy out the kernel image for create-efi command
-        objcopy -j .linux -O binary kernel.efi "$target/work/vmlinuz-$kver"
+    # copy out the kernel image for create-efi command
+    objcopy -j .linux -O binary "$target"/kernel/kernel.efi "$target/work/vmlinuz-$kver"
 
-        cp -a kernel.efi "$target/backup/"
-    )
+    cp -a "$target"/kernel/kernel.efi "$target/backup/"
 
-    (
-        cd "$target/work"
-        # this works on 20.04 but not on 18.04
-        unmkinitramfs initrd unpacked-initrd
-    )
-
+    # this works on 20.04 but not on 18.04
+    unmkinitramfs "$target"/work/initrd "$target"/work/unpacked-initrd
+    
     # copy the unpacked initrd to use as the target skeleton
     cp -ar "$target/work/unpacked-initrd" "$target/skeleton"
 
@@ -98,20 +90,22 @@ extract_kernel() {
 
 }
 
-prepare_kernel() {
+prepare() {
     local target="$1"
 
-    if [[ -z "$target" ]]; then
-        echo "usage: repack <extract-tree>"
+    if [ -z "$target" ]; then
+        echo "repack-kernel: missing target for prepare"
         exit 1
     fi
 
     target=$(realpath "$target")
+    
+    local kver
     kver="$(get_kver "$target/kernel")"
 
     (
         # all the skeleton edits go to a local copy of distro directory
-        skeletondir="$target/skeleton"
+        local skeletondir="$target/skeleton"
 
         cd "$target/work"
         # XXX: need to be careful to build an initrd using the right kernel
@@ -146,27 +140,27 @@ prepare_kernel() {
 cull_firmware() {
     local target="$1"
 
-    if [[ -z "$target" ]]; then
-        echo "usage: cull-firmware <extract-tree>"
+    if [ -z "$target" ]; then
+        echo "repack-kernel: missing target for cull-firmware"
         exit 1
     fi
-    (
-        # XXX: drop ~450MB+ of firmware which should not be needed in under qemu
-        # or the cloud system
-        cd "$target/kernel"
-        rm -rf firmware/*
-    )
+    
+    # XXX: drop ~450MB+ of firmware which should not be needed in under qemu
+    # or the cloud system
+    rm -rf "$target"/kernel/firmware/*
 }
 
 cull_modules() {
     local target="$1"
 
-    if [[ -z "$target" ]]; then
-        echo "usage: cull-modules <extract-tree>"
+    if [ -z "$target" ]; then
+        echo "repack-kernel: missing target for cull-modules"
         exit 1
     fi
 
     target=$(realpath "$target")
+    
+    local kver
     kver="$(get_kver "$target/kernel")"
 
     (
@@ -194,42 +188,43 @@ cull_modules() {
 pack() {
     local target="$1"
 
-    if [[ -z "$target" ]]; then
-        echo "usage: pack <extract-tree> <opts to snap pack>"
+    if [ -z "$target" ]; then
+        echo "repack-kernel: missing target for pack"
         exit 1
     fi
     snap pack "${@:2}" "$target/kernel" 
 }
 
 main() {
-    opt="$1"
-    shift || true
+    if [ $# -eq 0 ]; then
+        show_help
+        exit 0
+    fi
 
-    if [[ -z "$opt" ]] || [[ "$opt" == "--help" ]]; then
+    local subcommand="$1"
+    local action=
+    while [ $# -gt 0 ]; do
+        case "$1" in
+            -h|--help)
+                show_help
+                exit 0
+                ;;
+            *)
+                action=$(echo "$subcommand" | tr '-' '_')
+                shift
+                break
+                ;;
+        esac
+    done
+
+    if [ -z "$(declare -f "$action")" ]; then
+        echo "repack-kernel: no such command: $subcommand" >&2
         show_help
         exit 1
     fi
 
-    case "$opt" in
-        setup)
-            setup_deps
-            ;;
-        extract)
-            extract_kernel "$@"
-            ;;
-        prepare)
-            prepare_kernel "$@"
-            ;;
-        cull-modules)
-            cull_modules "$@"
-            ;;
-        cull-firmware)
-            cull_firmware "$@"
-            ;;
-        pack)
-            pack "$@"
-            ;;
-    esac
+    "$action" "$@"
 }
 
 main "$@"
+
